version: '3'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: MySup3rPassword!
    restart: always
    image: postgres
    ports:
      - 5432:5432
  api:
    build:
      context: .
      dockerfile: ./production.api.dockerfile
    command: sh -c "gunicorn --bind 0.0.0.0:8000 coretabs.wsgi --timeout 90 --log-level=DEBUG"
    #volumes:
    #  - ./src/venv/:/djangoapp/venv/
    environment:
      SPA_BASE_URL: https://coretabs.net
      DATABASE_URL: postgres://app_user:MySup3rPassword!@db/app_db
      SECRET_KEY: zby2z^8x2(zlhlfa233=-ji9eq)$$&^aa-vjs@8a)u0h0t#eqh^
      EMAIL_HOST: your_smtp_server
      EMAIL_HOST_USER: your_email
      EMAIL_HOST_PASSWORD: your_email_pass
      DISCOURSE_HOST: discourse_domain_name
      DISCOURSE_SSO_SECRET: your_discourse_secret
      DISCOURSE_API_KEY: 123456
      DISCOURSE_API_USERNAME: your_discourse_user
      MANAGERS_EMAILS: manager1@email.com;manager2@email.com
      SENTRY_DSN: https://your_sentry_dns
    links:
      - db:db
    ports:
      - "8000:8000"
  spa:
    build:
      context: .
      dockerfile: ./production.spa.dockerfile
    command: sh -c "npm start"
    ports:
      - "8001:3000"
    environment:
      VUE_APP_API_BASE_URL: https://api.coretabs.net
    