version: '3'

services:
  api:
    container_name: 'coretabs_academy_django_api_dev'
    build:
      context: .
      dockerfile: ./development.api.dockerfile
    volumes:
      - ./src/api/:/djangoapp/
      - /djangoapp/venv/
    ports:
      - "8000:8000"
    command: sh -c "virtualenv venv && source ./venv/bin/activate && pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    #command: sh -c "tail -f /dev/null"
  spa:
    container_name: 'coretabs_academy_spa_dev'
    image: "node:alpine"
    working_dir: /home/node/app
    volumes:
      - ./src/spa/:/home/node/app
    ports:
      - "8081:8080"
    command: sh -c "yarn install && yarn run serve"