version: '3'

services:
  db:
    env_file:
      - secrets.db.env
    restart: always
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /var/academy-db:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: ./production.api.dockerfile
    command: sh -c "memcached -d -u root -s /tmp/memcached.sock && gunicorn --bind 0.0.0.0:8000 coretabs.wsgi --timeout 90 --log-level=DEBUG"

    volumes:
      - /var/academy-media:/djangoapp/media
    #  - ./src/venv/:/djangoapp/venv/
    environment:
      HOST_ENV: $HOST_ENV
      SPA_BASE_URL: $SPA_BASE_URL
      API_BASE_URL: $API_BASE_URL
    env_file:
      - secrets.api.env
    links:
      - db:db
    ports:
      - "8000:8000"
  spa:
    build:
      context: .
      dockerfile: ./production.spa.dockerfile
      args:
        API_BASE_URL: $API_BASE_URL
        MAINTENANCE_MODE: $MAINTENANCE_MODE
    command: sh -c "npm start"
    ports:
      - "8001:3000"